apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

namespace: axiom-system-staging

labels:
- pairs:
    environment: staging
  includeSelectors: false

replicas:
- name: super-agent
  count: 2

images:
- name: axiom-system/super-agent
  newTag: staging-v1.0.0
