apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

namespace: axiom-system-dev

labels:
- pairs:
    environment: dev
  includeSelectors: false

replicas:
- name: super-agent
  count: 1

images:
- name: axiom-system/super-agent
  newTag: dev-latest
